title: Rate Our Cops
author: rateourcops.com
email: 
description: >-
    A movement for the people's wish to end racial injustice. We offer cops to be held publicly accountable to regain our trust.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://rateourcops.com/" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
